import React from 'react';

const PaymentReceipt = ({ data }) => {
    if (!data) return null;

    const {
        id,
        amount,
        paymentStatus,
        approvalStatus,
        paymentDate,
        createdAt,
        invoice,
        collectedBy
    } = data;

    const retailerName = invoice?.order?.retailer?.shopName || invoice?.customerName;
    const retailerAddress = invoice?.order?.retailer?.address || invoice?.customerAddress;
    const billNo = invoice?.invoiceNumber;
    const billDate = invoice?.invoiceDate;
    const billTotal = invoice?.netTotal;

    // Format Date: 2026-02-24
    // Format Time: 22:41 PM
    const createdDateObj = new Date(createdAt);
    const formattedDate = createdDateObj.toISOString().split('T')[0];
    let hours = createdDateObj.getHours();
    const minutes = createdDateObj.getMinutes().toString().padStart(2, '0');
    const ampm = hours >= 12 ? 'PM' : 'AM';
    hours = hours % 12;
    hours = hours ? hours : 12; // the hour '0' should be '12'
    const formattedTime = `${hours}:${minutes} ${ampm}`;

    return (
        <div className="payment-receipt-print-only" style={{
            width: '80mm',
            padding: '5mm',
            backgroundColor: 'white',
            color: 'black',
            fontFamily: "'Courier New', Courier, monospace",
            fontSize: '12px',
            lineHeight: '1.4'
        }}>
            <div style={{ textAlign: 'center', fontWeight: 'bold', fontSize: '14px', marginBottom: '10px' }}>
                A.C.M AGENCIES
            </div>

            <div style={{ marginBottom: '5px' }}>
                Pay No: {id}
            </div>
            <div style={{ marginBottom: '5px' }}>
                Customer: {retailerName?.toUpperCase()}
            </div>
            <div style={{ marginBottom: '10px' }}>
                Date: {formattedDate} | Time: {formattedTime}
            </div>

            <div style={{ borderTop: '1px dashed black', paddingBottom: '2px' }}></div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', marginBottom: '5px' }}>
                <span>DESCRIPTION</span>
                <span>AMOUNT</span>
            </div>
            <div style={{ borderTop: '1px dashed black', marginBottom: '10px' }}></div>

            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '2px' }}>
                <span style={{ fontWeight: 'bold' }}>Bill #{billNo}</span>
                <span>{parseFloat(amount).toFixed(2)}</span>
            </div>
            <div style={{ fontSize: '10px', color: '#333' }}>
                SALES ({billDate})
            </div>
            <div style={{ fontSize: '10px', color: '#333', marginBottom: '10px' }}>
                Bill Total: {parseFloat(billTotal).toFixed(2)}
            </div>

            <div style={{ borderTop: '1px dashed black', paddingBottom: '2px' }}></div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontWeight: 'bold', fontSize: '14px', marginBottom: '10px' }}>
                <span>TOTAL COLLECTED:</span>
                <span>{parseFloat(amount).toFixed(2)}</span>
            </div>
            <div style={{ borderTop: '1px dashed black', marginBottom: '15px' }}></div>

            <div style={{ textAlign: 'center', fontSize: '10px' }}>
                Generated by: {collectedBy?.name || 'System'}
            </div>

            <style dangerouslySetInnerHTML={{
                __html: `
        @media screen {
          .payment-receipt-print-only {
            display: none;
          }
        }
        @media print {
          body * {
            visibility: hidden;
          }
          .payment-receipt-print-only, .payment-receipt-print-only * {
            visibility: visible;
          }
          .payment-receipt-print-only {
            position: absolute;
            left: 0;
            top: 0;
            width: 80mm;
            display: block !important;
          }
        }
      `}} />
        </div>
    );
};

export default PaymentReceipt;
